export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const REQUEST_FAILED = "REQUEST_FAILED";

//* #################### categorias ##################
export const CATEGORIES_REQUEST = "CATEGORIES_REQUEST";
export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS";
export const CATEGORIES_FAILED = "CATEGORIES_FAILED";
export const CATEGORIES_REQUEST_PAGE = "CATEGORIES_REQUEST_PAGE";
export const CATEGORIES_REQUEST_SEACH = "CATEGORIES_REQUEST_SEACH";
export const CATEGORIES_REQUEST_VISIBLE = "CATEGORIES_REQUEST_VISIBLE";

//* #################### subcategorias ##################
export const SUBCATEGORIES_REQUEST = "SUBCATEGORIES_REQUEST";
export const SUBCATEGORIES_SUCCESS = "SUBCATEGORIES_SUCCESS";
export const SUBCATEGORIES_FAILED = "SUBCATEGORIES_FAILED";
export const SUBCATEGORIES_REQUEST_PAGE = "SUBCATEGORIES_REQUEST_PAGE";
export const SUBCATEGORIES_REQUEST_SEACH = "SUBCATEGORIES_REQUEST_SEACH";
export const SUBCATEGORIES_REQUEST_VISIBLE = "SUBCATEGORIES_REQUEST_VISIBLE";
